spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/test-service
    driver-class-name: org.postgresql.Driver
    username: cnvmxm
    password: cnvmxm
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
server:
  port: 8085
